// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package rambpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadRamBPF returns the embedded CollectionSpec for ramBPF.
func loadRamBPF() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RamBPFBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ramBPF: %w", err)
	}

	return spec, err
}

// loadRamBPFObjects loads ramBPF and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ramBPFObjects
//	*ramBPFPrograms
//	*ramBPFMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRamBPFObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRamBPF()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ramBPFSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ramBPFSpecs struct {
	ramBPFProgramSpecs
	ramBPFMapSpecs
	ramBPFVariableSpecs
}

// ramBPFProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ramBPFProgramSpecs struct {
}

// ramBPFMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ramBPFMapSpecs struct {
}

// ramBPFVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ramBPFVariableSpecs struct {
}

// ramBPFObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRamBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type ramBPFObjects struct {
	ramBPFPrograms
	ramBPFMaps
	ramBPFVariables
}

func (o *ramBPFObjects) Close() error {
	return _RamBPFClose(
		&o.ramBPFPrograms,
		&o.ramBPFMaps,
	)
}

// ramBPFMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRamBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type ramBPFMaps struct {
}

func (m *ramBPFMaps) Close() error {
	return _RamBPFClose()
}

// ramBPFVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRamBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type ramBPFVariables struct {
}

// ramBPFPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRamBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type ramBPFPrograms struct {
}

func (p *ramBPFPrograms) Close() error {
	return _RamBPFClose()
}

func _RamBPFClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rambpf_bpfel.o
var _RamBPFBytes []byte
