// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package cpubpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cpuBPFCpuTimeConsumed struct {
	_  structs.HostLayout
	Ns uint64
}

type cpuBPFPidKey struct {
	_   structs.HostLayout
	Pid uint32
}

type cpuBPFPidStartTime struct {
	_       structs.HostLayout
	StartNs uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	cpuBPFMapCpuPidStart        = "cpu_pid_start"
	cpuBPFMapCpuTimeNs          = "cpu_time_ns"
	cpuBPFProgHandleSchedSwitch = "handle_sched_switch"
	cpuBPFVarTargetTgid         = "target_tgid"
)

// loadCpuBPF returns the embedded CollectionSpec for cpuBPF.
func loadCpuBPF() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CpuBPFBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cpuBPF: %w", err)
	}

	return spec, err
}

// loadCpuBPFObjects loads cpuBPF and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cpuBPFObjects
//	*cpuBPFPrograms
//	*cpuBPFMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCpuBPFObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadCpuBPF()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cpuBPFSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuBPFSpecs struct {
	cpuBPFProgramSpecs
	cpuBPFMapSpecs
	cpuBPFVariableSpecs
}

// cpuBPFProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuBPFProgramSpecs struct {
	HandleSchedSwitch *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
}

// cpuBPFMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuBPFMapSpecs struct {
	CpuPidStart *ebpf.MapSpec `ebpf:"cpu_pid_start"`
	CpuTimeNs   *ebpf.MapSpec `ebpf:"cpu_time_ns"`
}

// cpuBPFVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuBPFVariableSpecs struct {
	TargetTgid *ebpf.VariableSpec `ebpf:"target_tgid"`
}

// cpuBPFObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCpuBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuBPFObjects struct {
	cpuBPFPrograms
	cpuBPFMaps
	cpuBPFVariables
}

func (o *cpuBPFObjects) Close() error {
	return _CpuBPFClose(
		&o.cpuBPFPrograms,
		&o.cpuBPFMaps,
	)
}

// cpuBPFMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCpuBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuBPFMaps struct {
	CpuPidStart *ebpf.Map `ebpf:"cpu_pid_start"`
	CpuTimeNs   *ebpf.Map `ebpf:"cpu_time_ns"`
}

func (m *cpuBPFMaps) Close() error {
	return _CpuBPFClose(
		m.CpuPidStart,
		m.CpuTimeNs,
	)
}

// cpuBPFVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCpuBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuBPFVariables struct {
	TargetTgid *ebpf.Variable `ebpf:"target_tgid"`
}

// cpuBPFPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCpuBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuBPFPrograms struct {
	HandleSchedSwitch *ebpf.Program `ebpf:"handle_sched_switch"`
}

func (p *cpuBPFPrograms) Close() error {
	return _CpuBPFClose(
		p.HandleSchedSwitch,
	)
}

func _CpuBPFClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cpubpf_bpfel.o
var _CpuBPFBytes []byte
