// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package nicbpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadNicBPF returns the embedded CollectionSpec for nicBPF.
func loadNicBPF() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NicBPFBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nicBPF: %w", err)
	}

	return spec, err
}

// loadNicBPFObjects loads nicBPF and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nicBPFObjects
//	*nicBPFPrograms
//	*nicBPFMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNicBPFObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadNicBPF()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nicBPFSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nicBPFSpecs struct {
	nicBPFProgramSpecs
	nicBPFMapSpecs
	nicBPFVariableSpecs
}

// nicBPFProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nicBPFProgramSpecs struct {
}

// nicBPFMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nicBPFMapSpecs struct {
}

// nicBPFVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nicBPFVariableSpecs struct {
}

// nicBPFObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNicBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type nicBPFObjects struct {
	nicBPFPrograms
	nicBPFMaps
	nicBPFVariables
}

func (o *nicBPFObjects) Close() error {
	return _NicBPFClose(
		&o.nicBPFPrograms,
		&o.nicBPFMaps,
	)
}

// nicBPFMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNicBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type nicBPFMaps struct {
}

func (m *nicBPFMaps) Close() error {
	return _NicBPFClose()
}

// nicBPFVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNicBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type nicBPFVariables struct {
}

// nicBPFPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNicBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type nicBPFPrograms struct {
}

func (p *nicBPFPrograms) Close() error {
	return _NicBPFClose()
}

func _NicBPFClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nicbpf_bpfel.o
var _NicBPFBytes []byte
