// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package diskbpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDiskBPF returns the embedded CollectionSpec for diskBPF.
func loadDiskBPF() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DiskBPFBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load diskBPF: %w", err)
	}

	return spec, err
}

// loadDiskBPFObjects loads diskBPF and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*diskBPFObjects
//	*diskBPFPrograms
//	*diskBPFMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDiskBPFObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadDiskBPF()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// diskBPFSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type diskBPFSpecs struct {
	diskBPFProgramSpecs
	diskBPFMapSpecs
	diskBPFVariableSpecs
}

// diskBPFProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type diskBPFProgramSpecs struct {
}

// diskBPFMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type diskBPFMapSpecs struct {
}

// diskBPFVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type diskBPFVariableSpecs struct {
}

// diskBPFObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDiskBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type diskBPFObjects struct {
	diskBPFPrograms
	diskBPFMaps
	diskBPFVariables
}

func (o *diskBPFObjects) Close() error {
	return _DiskBPFClose(
		&o.diskBPFPrograms,
		&o.diskBPFMaps,
	)
}

// diskBPFMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDiskBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type diskBPFMaps struct {
}

func (m *diskBPFMaps) Close() error {
	return _DiskBPFClose()
}

// diskBPFVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDiskBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type diskBPFVariables struct {
}

// diskBPFPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDiskBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type diskBPFPrograms struct {
}

func (p *diskBPFPrograms) Close() error {
	return _DiskBPFClose()
}

func _DiskBPFClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed diskbpf_bpfel.o
var _DiskBPFBytes []byte
