// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type kernelBPFCpuTimeConsumed struct {
	_  structs.HostLayout
	Ns uint64
}

type kernelBPFCpuTimeKey struct {
	_    structs.HostLayout
	Tgid uint32
	Cpu  uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	kernelBPFMapCpuTimeNs               = "cpu_time_ns"
	kernelBPFProgHandleSchedStatRuntime = "handle_sched_stat_runtime"
	kernelBPFVarTargetTgid              = "target_tgid"
)

// loadKernelBPF returns the embedded CollectionSpec for kernelBPF.
func loadKernelBPF() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KernelBPFBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kernelBPF: %w", err)
	}

	return spec, err
}

// loadKernelBPFObjects loads kernelBPF and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kernelBPFObjects
//	*kernelBPFPrograms
//	*kernelBPFMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKernelBPFObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadKernelBPF()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kernelBPFSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelBPFSpecs struct {
	kernelBPFProgramSpecs
	kernelBPFMapSpecs
	kernelBPFVariableSpecs
}

// kernelBPFProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelBPFProgramSpecs struct {
	HandleSchedStatRuntime *ebpf.ProgramSpec `ebpf:"handle_sched_stat_runtime"`
}

// kernelBPFMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelBPFMapSpecs struct {
	CpuTimeNs *ebpf.MapSpec `ebpf:"cpu_time_ns"`
}

// kernelBPFVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelBPFVariableSpecs struct {
	TargetTgid *ebpf.VariableSpec `ebpf:"target_tgid"`
}

// kernelBPFObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKernelBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelBPFObjects struct {
	kernelBPFPrograms
	kernelBPFMaps
	kernelBPFVariables
}

func (o *kernelBPFObjects) Close() error {
	return _KernelBPFClose(
		&o.kernelBPFPrograms,
		&o.kernelBPFMaps,
	)
}

// kernelBPFMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKernelBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelBPFMaps struct {
	CpuTimeNs *ebpf.Map `ebpf:"cpu_time_ns"`
}

func (m *kernelBPFMaps) Close() error {
	return _KernelBPFClose(
		m.CpuTimeNs,
	)
}

// kernelBPFVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKernelBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelBPFVariables struct {
	TargetTgid *ebpf.Variable `ebpf:"target_tgid"`
}

// kernelBPFPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKernelBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelBPFPrograms struct {
	HandleSchedStatRuntime *ebpf.Program `ebpf:"handle_sched_stat_runtime"`
}

func (p *kernelBPFPrograms) Close() error {
	return _KernelBPFClose(
		p.HandleSchedStatRuntime,
	)
}

func _KernelBPFClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kernelbpf_bpfel.o
var _KernelBPFBytes []byte
